name: Athene2 Guide
markdown: redcarpet
pygments: true
baseurl: /athene2-guide
# baseurl: /
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks